---
title: <span style="color:#034a94"> **Validación cruzada**</span>
author: "Modelos Estadísticos para la toma de decisiones"
output: html_document
css: style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = NA, warning = FALSE, message = FALSE)
# colores
c1="#FF7F00"
c2="#=EB0C6"
c3="#034A94"
c4="#686868"
color2=c(c1,c2)
library(memisc)
library(MASS)
library(lattice)
library(stats)
# install.packages("learnr")          # solo una vez
# install.packages("devtools")     # solo una vez
# devtools::install_github("dgonxalex80/paqueteMOD", force = TRUE) #descarga paquete nivelatorioEST
library(paqueteMOD)
library(tidyverse)
data("dataMat")
# dataMat = sample(dataMat, 1000, replace = TRUE)
glm(gana ~ nota , family = binomial(link = "logit"), data = dataMat) -> modelo1
summary(modelo1) 
```

```{r}
library(caret)
table(dataMat$gana) %>% 
  prop.table()


```

```{r}
glm(gana ~ nota , family = binomial(link = "logit"), data = dataMat) -> modelo1
summary(modelo1) 
```
```{r}
library(caret)

# separacion de muetras
ntrain <- nrow(dataMat)*0.6
ntest <- nrow(dataMat)*0.4

set.seed(123)
index_train<-sample(1:nrow(dataMat),size = ntrain)
train<-dataMat[index_train,]  # muestra de entrenamiento
test<-dataMat[-index_train,]  # muestra de prueba

# matriz de confucion
valor_pronosticado <- predict(modelo1,test,type = "response")
niveles_pronosticados <- ifelse(valor_pronosticado >0.5, "Si","No") %>%
  factor(.)

confusionMatrix(niveles_pronosticados, test$gana )
```
```{r}
library(ROSE)
# oversampling
train.blc <- ovun.sample(gana~., data=train, 
                         p=0.5, seed=1, 
                         method="over")$data

test.blc <- ovun.sample(gana~., data=test, 
                         p=0.5, seed=1, 
                         method="over")$data
```


```{r}

glm(gana ~ nota , family = binomial(link = "logit"), data = train.blc) -> modelo2
summary(modelo1) 

# matriz de confucion
valor_pronosticado <- predict(modelo2,test.blc,type = "response")
niveles_pronosticados <- ifelse(valor_pronosticado >0.5, "Si","No") %>%
  factor(.)

confusionMatrix(niveles_pronosticados, test.blc$gana )
```





```{r}
library(paqueteMOD)
library(tidyverse)
data("dataMat")
dataMat = sample(dataMat, 2000, replace = TRUE)


# separacion de muetras
ntrain <- nrow(dataMat)*0.6
ntest <- nrow(dataMat)*0.4

set.seed(123)
index_train<-sample(1:nrow(dataMat),size = ntrain)
train<-dataMat[index_train,]  # muestra de entrenamiento
test<-dataMat[-index_train,]  # muestra de prueba




library(ROSE)
# oversampling
train.blc <- ovun.sample(gana~., data=train, 
                         p=0.5, seed=1, 
                         method="over")$data

test.blc <- ovun.sample(gana~., data=test, 
                         p=0.5, seed=1, 
                         method="over")$data
```


```{r}

glm(gana ~ nota , family = binomial(link = "logit"), data = train.blc) -> modelo2
summary(modelo1) 

# matriz de confucion
valor_pronosticado <- predict(modelo2,test.blc,type = "response")
niveles_pronosticados <- ifelse(valor_pronosticado >0.5, "Si","No") %>%
  factor(.)

confusionMatrix(niveles_pronosticados, test.blc$gana )
```





















  